export const navbarData=[
    {
        routeLink:'dashboard-m',
        icon:'assessment',
        label:'Dashboard'
    },
    {
        routeLink:'pedidos',
        icon:'reorder-icon',
        label:'Pedidos'
    },
    {
        routeLink:'perfil',
        icon:'person',
        label:'Perfil'
    },
    {
        routeLink:'/',
        icon:'logout',
        label:'Salir'
    }
]