export const navbarData=[
    {
        routeLink:'dashboard',
        icon:'home',
        label:'Dashboard'
    },
    {
        routeLink:'productos',
        icon:'shopping_cart_checkout',
        label:'Productos'
    },
    {
        routeLink:'perfil',
        icon:'person',
        label:'Perfil'
    },
    {
        routeLink:'pedidos',
        icon:'reorder-icon',
        label:'Pedidos'
    },
    {
        routeLink:'/login',
        icon:'logout',
        label:'Salir'
    }
]