export const navbarData=[
    {
        routeLink:'dashboard',
        icon:'assessment',
        label:'Dashboard'
    },
    {
        routeLink:'productos',
        icon:'agriculture',
        label:'Productos'
    },
    {
        routeLink:'categorias',
        icon:'category',
        label:'Categorias'
    },
    {
        routeLink:'/',
        icon:'logout',
        label:'Salir'
    }
]